# Generated by Django 5.0.6 on 2024-10-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='last_updaet',
            new_name='last_update',
        ),
        migrations.AddField(
            model_name='chat',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
