# Generated by Django 5.0.6 on 2024-10-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_last_updaet_chat_last_update_chat_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='blocker',
            field=models.IntegerField(default=-1),
        ),
    ]
