# Generated by Django 5.0.4 on 2024-05-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0002_alter_friend_request_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to='usercontent.profile'),
        ),
    ]
