# Generated by Django 5.0.4 on 2024-05-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0004_alter_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
