# Generated by Django 5.0.4 on 2024-07-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0009_profile_access_token_profile_remote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
