# Generated by Django 5.0.4 on 2024-07-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0010_profile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_request',
            name='receivername',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='friend_request',
            name='sendername',
            field=models.CharField(default='', max_length=100),
        ),
    ]
