# Generated by Django 5.0.4 on 2024-07-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0011_friend_request_receivername_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_request',
            name='receivername',
        ),
        migrations.RemoveField(
            model_name='friend_request',
            name='sendername',
        ),
    ]
