# Generated by Django 5.0.4 on 2024-08-05 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0012_remove_friend_request_receivername_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='receivernotf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recivernotf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='sendernotf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sendernotf', to=settings.AUTH_USER_MODEL),
        ),
    ]
