# Generated by Django 5.0.4 on 2024-09-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0015_profile_ruser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
