# Generated by Django 5.0.4 on 2024-10-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0016_notification_notification_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_count',
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
