# Generated by Django 5.0.4 on 2024-10-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0018_remove_profile_bio_profile_tourn_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tourn_name',
            new_name='tournament_name',
        ),
    ]
