# Generated by Django 5.0.4 on 2024-10-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0020_alter_profile_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tournament_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
