# Generated by Django 5.0.4 on 2024-11-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0022_remove_profile_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='access_token',
        ),
    ]
