# Generated by Django 5.0.4 on 2024-11-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0024_alter_profile_friends_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_request',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='usercontent.profile'),
        ),
        migrations.AlterField(
            model_name='friend_request',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='usercontent.profile'),
        ),
    ]
