# Generated by Django 5.0.4 on 2024-11-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0026_friend_request_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='usercontent.profile'),
        ),
    ]
