# Generated by Django 5.0.6 on 2024-07-17 12:10

import app.enums
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='four players', max_length=50)),
                ('status', models.CharField(choices=[('PN', 'pending'), ('ST', 'start'), ('EN', 'end')], default='pending', max_length=50)),
                ('round', models.CharField(choices=app.enums.Round.choices, default='half', max_length=50)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('size', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='player_x', max_length=100)),
                ('username', models.CharField(max_length=100, null=True)),
                ('profile_id', models.IntegerField(default=0)),
                ('img_url', models.URLField(null=True)),
                ('won', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trn_players', to='app.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='matche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('QU', 'quarter'), ('HF', 'half'), ('FN', 'final')], default='half', max_length=50)),
                ('status', models.CharField(choices=[('UNP', 'unplayed'), ('PLY', 'played')], default='unplayed', max_length=50)),
                ('player1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matche_p1', to='app.player')),
                ('player2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matche_p2', to='app.player')),
                ('winner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_win', to='app.player')),
                ('tourn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app.tournament')),
            ],
        ),
    ]
