# Generated by Django 5.0.6 on 2024-07-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matche',
            name='p1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matche',
            name='p2_score',
            field=models.IntegerField(default=0),
        ),
    ]
