# Generated by Django 5.0.6 on 2024-07-30 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_matche_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matche',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1_matches', to='app.player'),
        ),
        migrations.AlterField(
            model_name='matche',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2_matches', to='app.player'),
        ),
    ]
