# Generated by Django 5.0.6 on 2024-08-10 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_matche_player1_alter_matche_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='matche',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
