# Generated by Django 5.0.6 on 2024-09-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_matche_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='goals_achieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals_received',
            field=models.IntegerField(default=0),
        ),
    ]
