# Generated by Django 5.0.4 on 2024-12-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
